eureka:
  client:
    enabled: false
spring:
  cloud:
    kubernetes:
      enabled: true
      reload:
        enabled: true
  datasource:
    db1:
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/micro_db1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true&failOverReadOnly=false
      password: '0123456788'
      username: root
    db2:
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/micro_db2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true&failOverReadOnly=false
      password: '0123456788'
      username: root
  
